id: 82851b330d704159aee0ba42b7aad29a
title: Toh_273-The_Twelve_Buddhas-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-007
  eft-text-version: 1.2.3 2020
